import React,{useState} from 'react';
import {Droplet} from 'lucide-react';
export function Account({api,onSignedIn,demo}){
 const[register,setRegister]=useState(false),[role,setRole]=useState('donor'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 return <div className="auth-screen"><section className="auth-card"><Droplet size={32}/><h1>LifeLink</h1><p>Coordinate real responses, with your own account.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);const b={email:f.get('email'),password:f.get('password')};if(register)Object.assign(b,{name:f.get('name'),role,consent:f.get('consent')==='on',area:f.get('area'),location:{lat:Number(f.get('lat')),lng:Number(f.get('lng'))},...(role==='donor'?{bloodGroup:f.get('bloodGroup')}:{})});try{const r=await api('/auth/'+(register?'register':'login'),'POST',b);onSignedIn(r.user);}catch(err){setError(err.message);}finally{setBusy(false);}}}>
 {register&&<><label>Account type<select value={role} onChange={e=>setRole(e.target.value)}><option value="donor">Donor</option><option value="hospital">Hospital coordinator</option></select></label><label>{role==='hospital'?'Institution name':'Your name'}<input name="name" required minLength={2}/></label></>}
 <label>Email<input name="email" type="email" required autoComplete="username"/></label><label>Password<input name="password" type="password" minLength={register?12:1} required autoComplete={register?'new-password':'current-password'}/></label>
 {register&&<><label>Area<input name="area" required placeholder="Adyar, Chennai"/></label>{role==='donor'&&<label>Blood group<select name="bloodGroup">{['A+','A-','B+','B-','AB+','AB-','O+','O-'].map(g=><option key={g}>{g}</option>)}</select></label>}<div className="form-row"><label>Latitude<input name="lat" type="number" step="any" min="-90" max="90" required/></label><label>Longitude<input name="lng" type="number" step="any" min="-180" max="180" required/></label></div><small>Use approximate coordinates. Your exact location is not shown in the public directory.</small><label className="consent-row"><input name="consent" type="checkbox" required/> I agree to store my profile and receive matching requests in my private inbox. Push notifications are optional.</label>{role==='hospital'&&<p>New institutions need administrator approval before creating requests.</p>}</>}
 {error&&<p className="red" role="alert">{error}</p>}<button className="primary wide" disabled={busy}>{busy?'Please wait…':register?'Create account':'Sign in'}</button></form><button className="text-button" onClick={()=>{setRegister(!register);setError('');}}>{register?'Already registered? Sign in':'Create a donor or hospital account'}</button>{demo&&<div className="demo-login"><b>Local fictional demo</b><p>Hospital: h1@lifelink.test<br/>Donor: d1@lifelink.test<br/>Admin: admin@lifelink.test</p><code>LifeLink-demo-2026!</code><p>Demo credentials exist only in temporary local mode.</p></div>}</section></div>;
}
export function Workflow({data,action,busy}){
 const[dates,setDates]=useState({}),[units,setUnits]=useState({}),[post,setPost]=useState({});
 return <section className="panel workflow"><h2>Appointments & collections</h2><p>Reservations are not collected blood. Hospitals confirm each step.</p><div className="workflow-grid">{data.appointments.map(a=><article key={a.id}><span className="eyebrow">{a.id}</span><h3>{data.donors.find(d=>d.id===a.donorId)?.name||a.donorId}</h3><p>{a.requestId} · {a.status}</p>{a.scheduledAt&&<small>Appointment: {new Date(a.scheduledAt).toLocaleString()}</small>}{a.status==='Collected'&&<b>{a.units} confirmed units</b>}{data.user.role==='hospital'&&<>{a.status==='Accepted'&&<><label>Appointment time<input aria-label={'Appointment time '+a.id} type="datetime-local" value={dates[a.id]||''} onChange={e=>setDates({...dates,[a.id]:e.target.value})}/></label><button className="primary" disabled={busy||!dates[a.id]} onClick={()=>action('/appointments/'+a.id,'PATCH',{status:'Appointment',scheduledAt:new Date(dates[a.id]).toISOString()})}>Schedule appointment</button></>}{a.status==='Appointment'&&<button className="primary" disabled={busy} onClick={()=>action('/appointments/'+a.id,'PATCH',{status:'Attended'})}>Confirm attendance</button>}{a.status==='Attended'&&<><label>Units confirmed<input type="number" min="1" max="2" value={units[a.id]||1} onChange={e=>setUnits({...units,[a.id]:Number(e.target.value)})}/></label><label className="consent-row"><input type="checkbox" checked={post[a.id]||false} onChange={e=>setPost({...post,[a.id]:e.target.checked})}/> Post these confirmed units to hospital inventory</label><button className="primary" disabled={busy} onClick={()=>action('/appointments/'+a.id,'PATCH',{status:'Collected',units:units[a.id]||1,addToInventory:post[a.id]||false})}>Confirm collection</button></>}{['Accepted','Appointment','Attended'].includes(a.status)&&<button className="text-button" disabled={busy} onClick={()=>action('/appointments/'+a.id,'PATCH',{status:'Cancelled'})}>Cancel reservation</button>}</>}</article>)}</div>{!data.appointments.length&&<p>No appointments yet. A donor acceptance creates a reservation.</p>}</section>;
}
export function Inbox({api,onRefresh}){
 const[alerts,setAlerts]=useState([]),[error,setError]=useState(''),[push,setPush]=useState('');
 React.useEffect(()=>{let active=true;const load=()=>api('/alerts').then(r=>{if(active)setAlerts(r.alerts);}).catch(e=>setError(e.message));load();const timer=setInterval(load,10000);return()=>{active=false;clearInterval(timer);};},[]);
 async function enable(){try{if(!('serviceWorker'in navigator)||!('PushManager'in window))throw Error('Web Push is not supported in this browser.');const config=await api('/push/config');if(!config.enabled)throw Error('Push delivery needs VAPID configuration. Your inbox still works.');const permission=await Notification.requestPermission();if(permission!=='granted')throw Error('Notification permission was not granted.');const registration=await navigator.serviceWorker.register(import.meta.env.BASE_URL+'sw.js');await navigator.serviceWorker.ready;const bytes=Uint8Array.from(atob(config.publicKey.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));const subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes});await api('/push/subscriptions','POST',subscription.toJSON());setPush('Push notifications enabled');}catch(e){setPush(e.message);}}
 return <section className="panel inbox"><div className="inbox-title"><h2>Your saved inbox</h2><button className="secondary" onClick={enable}>Enable push notifications</button><button className="text-button" onClick={async()=>{await api('/push/subscriptions','DELETE');const r=await navigator.serviceWorker?.getRegistration();const s=await r?.pushManager.getSubscription();await s?.unsubscribe();setPush('Push notifications disabled');}}>Disable push</button></div>{push&&<p role="status">{push}</p>}{error&&<p className="red">{error}</p>}{alerts.map(a=><article className="inbox-row" key={a.id}><div><b>{a.request?.bloodGroup} · {a.request?.units} units</b><p>{a.requestId} · {a.request?.status} · {a.distanceKm} km</p><small>{a.respondedAt?'Responded':a.seenAt?'Seen':'New'} · {new Date(a.createdAt).toLocaleString()}</small></div>{!a.seenAt&&<button className="secondary" onClick={async()=>{await api('/alerts/'+a.id+'/seen','PATCH',{});setAlerts(prev=>prev.map(x=>x.id===a.id?{...x,seenAt:new Date().toISOString()}:x));}}>Mark seen</button>}</article>)}{!alerts.length&&<p>No saved alerts yet. Alerts stay here after reconnecting.</p>}</section>;
}
export function Approvals({api,action}){
 const[rows,setRows]=useState([]);
 React.useEffect(()=>{api('/admin/hospitals').then(r=>setRows(r.hospitals));},[]);
 return <section className="panel workflow"><h2>Institution approvals</h2><p>Review the institution outside this demo before approving access.</p>{rows.map(h=><div className="inbox-row" key={h.id}><div><b>{h.name}</b><p>{h.area} · {h.approved?'Approved':'Pending review'}</p></div><button className="secondary" onClick={async()=>{await action('/admin/hospitals/'+h.id,'PATCH',{approved:!h.approved});setRows(rows.map(x=>x.id===h.id?{...x,approved:!h.approved}:x));}}>{h.approved?'Revoke approval':'Approve institution'}</button></div>)}</section>;
}
export function RequestAssistant({api,onDraft}){
 const[text,setText]=useState(''),[draft,setDraft]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 return <div className="assistant-box"><b>Gemini request assistant</b><p>No patient names, contact details or clinical notes. Only group, units, area and request preferences are sent to Gemini.</p><textarea aria-label="Describe blood request" value={text} onChange={e=>setText(e.target.value)} maxLength={500} placeholder="Need 2 O+ units near Adyar this evening"/><button type="button" className="secondary" disabled={busy||text.length<5} onClick={async()=>{setBusy(true);setError('');try{const r=await api('/assistant/draft','POST',{text});setDraft(r.draft);}catch(e){setError(e.message);}finally{setBusy(false);}}}>{busy?'Extracting…':'Create draft with Gemini'}</button>{error&&<p role="alert" className="red">{error}</p>}{draft&&<div className="assistant-review"><b>Review the extracted draft</b><p>Group: {draft.bloodGroup||'Not specified'} · Units: {draft.units||'Not specified'}<br/>Area: {draft.area||'Not specified'} · Time: {draft.requestedTimeText||'Not specified'}</p><p>Still needed: {draft.missingFields.join(', ')||'None'}</p><p>The request uses your institution's location. Time text is not an appointment.</p><button type="button" className="secondary" onClick={()=>onDraft(draft)}>Apply draft to form</button></div>}</div>;
}
