import React,{useState} from 'react';
import {Droplet} from 'lucide-react';
export function Account({api,onSignedIn,demo}){
 const[register,setRegister]=useState(false),[role,setRole]=useState('donor'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 return <div className="auth-screen"><section className="auth-card"><Droplet size={32}/><h1>LifeLink</h1><p>Coordinate real responses, with your own account.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);const b={email:f.get('email'),password:f.get('password')};if(register)Object.assign(b,{name:f.get('name'),role,consent:f.get('consent')==='on',area:f.get('area'),location:{lat:Number(f.get('lat')),lng:Number(f.get('lng'))},...(role==='donor'?{bloodGroup:f.get('bloodGroup')}:{}));try{const r=await api('/auth/'+(register?'register':'login'),'POST',b);onSignedIn(r.user);}catch(err){setError(err.message);}finally{setBusy(false);}}}>
 {register&&<><label>Account type<select value={role} onChange={e=>setRole(e.target.value)}><option value="donor">Donor</option><option value="hospital">Hospital coordinator</option></select></label><label>{role==='hospital'?'Institution name':'Your name'}<input name="name" required minLength={2}/></label></>}
 <label>Email<input name="email" type="email" required autoComplete="username"/></label><label>Password<input name="password" type="password" minLength={register?12:1} required autoComplete={register?'new-password':'current-password'}/></label>
 {register&&<><label>Area<input name="area" required placeholder="Adyar, Chennai"/></label>{role==='donor'&&<label>Blood group<select name="bloodGroup">{['A+','A-','B+','B-','AB+','AB-','O+','O-'].map(g=><option key={g}>{g}</option>)}</select></label>}<div className="form-row"><label>Latitude<input name="lat" type="number" step="any" min="-90" max="90" required/></label><label>Longitude<input name="lng" type="number" step="any" min="-180" max="180" required/></label></div><small>Use approximate coordinates. Your exact location is not shown in the public directory.</small><label className="consent-row"><input name="consent" type="checkbox" required/> I agree to store my profile and receive matching requests in my private inbox. Push notifications are optional.</label>{role==='hospital'&&<p>New institutions need administrator approval before creating requests.</p>}</>}
 {error&&<p className="red" role="alert">{error}</p>}<button className="primary wide" disabled={busy}>{busy?'Please wait…':register?'Create account':'Sign in'}</button></form><button className="text-button" onClick={()=>{setRegister(!register);setError('');}}>{register?'Already registered? Sign in':'Create a donor or hospital account'}</button>{demo&&<div className="demo-login"><b>Local fictional demo</b><p>Hospital: h1@lifelink.test<br/>Donor: d1@lifelink.test<br/>Admin: admin@lifelink.test</p><code>LifeLink-demo-2026!</code><p>Demo credentials exist only in temporary local mode.</p></div>}</section></div>;
}
export function Workflow({data,action,busy}){
 const[dates,setDates]=useState({}),[units,setUnits]=useState({}),[post,setPost]=useState({});
 return <section className="panel workflow"><h2>Appointments & collections</h2><p>Reservations are not collected blood. Hospitals confirm each step.</p><div className="workflow-grid">{data.appointments.map(a=><article key={a.id}><span className="eyebrow">{a.id}</span><h3>{data.donors.find(d=>d.id===a.donorId)?.name||a.donorId}</h3><p>{a.requestId} · {a.status}</p>{a.scheduledAt&&<small>Appointment: {new Date(a.scheduledAt).toLocaleString()}</small>}{a.status==='Collected'&&<b>{a.units} confirmed units</b>}{data.user.role==='hospital'&&<>{a.status==='Accepted'&&<><label>Appointment time<input aria-label={'Appointment time '+a.id} type="datetime-local" value={dates[a.id]||''} onChange={e=>setDates({...dates,[a.id]:e.target.value})}/></label><button className="primary" disabled={busy||!dates[a.id]} onClick={()=>action('/appointments/'+a.id,'PATCH',{status:'Appointment',scheduledAt:new Date(dates[a.id]).toISOString()})}>Schedule appointment</button></>}{a.status==='Appointment'&&<button className="primary" disabled={busy} onClick={()=>action('/appointments/'+a.id,'PATCH',{status:'Attended'})}>Confirm attendance</button>}{a.status==='Attended'&&<><label>Units confirmed<input type="number" min="1" max="2" value={units[a.id]||1} onChange={e=>setUnits({...units,[a.id]:Number(e.target.value)})}/></label><label className="consent-row"><input type="checkbox" checked={post[a.id]||false} onChange={e=>setPost({...post,[a.id]:e.target.checked})}/> Post these confirmed units to hospital inventory</label><button className="primary" disabled={busy} onClick={()=>action('/appointments/'+a.id,'PATCH',{status:'Collected',units:units[a.id]||1,addToInventory:post[a.id]||false})}>Confirm collection</button></>}{['Accepted','Appointment','Attended'].includes(a.status)&&<button className="text-button" disabled={busy} onClick={()=>action('/appointments/'+a.id,'PATCH',{status:'Cancelled'})}>Cancel reservation</button>}</>}</article>)}</div>{!data.appointments.length&&<p>No appointments yet. A donor acceptance creates a reservation.</p>}</section>;
}
