import {test} from 'node:test';import assert from 'node:assert/strict';import {io} from 'socket.io-client';
const base=process.env.TEST_URL;
const accounts={};
async function login(email){const r=await fetch(base+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password:'LifeLink-demo-2026!'})});assert.equal(r.status,200);return r.headers.get('set-cookie').split(';')[0];}
async function api(path,method='GET',body,cookie=accounts.hospital){const r=await fetch(base+'/api'+path,{method,headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},body:body?JSON.stringify(body):undefined});const data=await r.json();return {status:r.status,data};}
let requestId,appointmentId;
test('anonymous access rejected and role sessions work',async()=>{assert.equal((await api('/state','GET',null,'')).status,401);accounts.hospital=await login('h1@lifelink.test');accounts.other=await login('h2@lifelink.test');accounts.donor=await login('d1@lifelink.test');accounts.admin=await login('admin@lifelink.test');const s=await api('/state');assert.equal(s.data.user.role,'hospital');assert.ok(s.data.requests.every(r=>r.hospitalId==='h1'));assert.ok(s.data.inventory.every(i=>i.hospitalId==='h1'));assert.ok(s.data.donors.every(d=>d.location===undefined));});
test('RBAC protects profiles, institutions and origins',async()=>{assert.equal((await api('/donors/d2','PATCH',{available:true},accounts.donor)).status,403);assert.equal((await api('/donors/d1','PATCH',{available:true})).status,403);assert.equal((await api('/inventory/O+','PATCH',{units:5},accounts.donor)).status,403);const r=await fetch(base+'/api/auth/logout',{method:'POST',headers:{Origin:'https://evil.invalid',Cookie:accounts.donor}});assert.equal(r.status,403);});
test('request creates persisted alert and authenticated live update',async()=>{const socket=io(base,{extraHeaders:{Cookie:accounts.donor},transports:['websocket']});await new Promise((resolve,reject)=>{socket.once('connect',resolve);socket.once('connect_error',reject);});const event=new Promise(resolve=>socket.once('donor:alert',resolve));const r=await api('/requests','POST',{hospitalId:'h1',bloodGroup:'O+',units:1,urgency:'Urgent',purpose:'Hospital requirement',radiusKm:15});assert.equal(r.status,201);requestId=r.data.request.id;const alert=await event;assert.equal(alert.request.id,requestId);socket.disconnect();const inbox=await api('/alerts','GET',null,accounts.donor);assert.ok(inbox.data.alerts.some(a=>a.requestId===requestId));const saved=inbox.data.alerts.find(a=>a.requestId===requestId);assert.equal((await api('/alerts/'+saved.id+'/seen','PATCH',{},accounts.donor)).status,200);});
test('acceptance reserves capacity but creates no collected units',async()=>{const r=await api('/requests/'+requestId+'/accept','POST',{donorId:'d1'},accounts.donor);assert.equal(r.status,200);assert.equal(r.data.collectedUnits,0);assert.equal((await api('/requests/'+requestId+'/accept','POST',{donorId:'d1'},accounts.donor)).status,409);const s=await api('/state');const a=s.data.appointments.find(a=>a.requestId===requestId);assert.equal(a.status,'Accepted');appointmentId=a.id;assert.equal((await api('/appointments/'+a.id,'PATCH',{status:'Attended'})).status,409);assert.equal((await api('/appointments/'+a.id,'PATCH',{status:'Appointment',scheduledAt:new Date(Date.now()+86400000).toISOString()},accounts.other)).status,404);});
test('collection workflow atomically records units and explicit inventory posting',async()=>{const before=(await api('/state')).data.inventory.find(i=>i.bloodGroup==='O+').units;assert.equal((await api('/appointments/'+appointmentId,'PATCH',{status:'Appointment',scheduledAt:new Date(Date.now()+86400000).toISOString()})).status,200);assert.equal((await api('/appointments/'+appointmentId,'PATCH',{status:'Attended'})).status,200);assert.equal((await api('/appointments/'+appointmentId,'PATCH',{status:'Collected',units:1,addToInventory:true})).status,200);assert.equal((await api('/appointments/'+appointmentId,'PATCH',{status:'Collected',units:1,addToInventory:true})).status,409);const s=(await api('/state')).data;assert.equal(s.requests.find(r=>r.id===requestId).status,'Fulfilled');assert.equal(s.requests.find(r=>r.id===requestId).collectedUnits,1);assert.equal(s.inventory.find(i=>i.bloodGroup==='O+').units,before+1);const alerts=(await api('/alerts','GET',null,accounts.donor)).data.alerts;assert.ok(alerts.find(a=>a.requestId===requestId).respondedAt);});
test('new institution needs explicit administrator approval',async()=>{const email='new-'+Date.now()+'@example.test';const r=await api('/auth/register','POST',{email,password:'Strong-demo-only-123!',name:'Fictional Hospital',role:'hospital',consent:true,area:'Adyar',location:{lat:13,lng:80}});assert.equal(r.status,201);const user=r.data.user;const auth=await fetch(base+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password:'Strong-demo-only-123!'})});const cookie=auth.headers.get('set-cookie').split(';')[0];const body={hospitalId:user.hospitalId,bloodGroup:'O+',units:1,urgency:'Standard',purpose:'Hospital requirement',radiusKm:15};assert.equal((await api('/requests','POST',body,cookie)).status,403);assert.equal((await api('/admin/hospitals/'+user.hospitalId,'PATCH',{approved:true},accounts.admin)).status,200);assert.equal((await api('/requests','POST',body,cookie)).status,201);});
test('push enrollment rejects arbitrary network endpoints',async()=>{assert.equal((await api('/push/subscriptions','POST',{endpoint:'https://internal.invalid',keys:{p256dh:'x'.repeat(30),auth:'x'.repeat(20)}},accounts.donor)).status,400);});
